services:
  urbanease-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urbanease-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - valkey
  valkey:
    image: valkey/valkey:latest
    container_name: urbanease-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes: 
      - valkey-data:/data

volumes:
  valkey-data: